### 모델 훈련
개별 파일(MF.py, KNN.py)에서도 훈련이 가능하지만, 최상위 모듈인 train.py를 사용하여 학습을 진행할 수 있습니다.</br>
train.py 모듈을 터미널에서 실행하는 것으로 학습할 수 있습니다.</br>
train.py와 함께 사용할 수 있는 arguments들은 다음과 같습니다.</br>

**mf 모델 학습용 arguments**
- --mf : Matrix Factorization 모델의 학습 여부를 결정하는 인자입니다. --mf 를 입력하는 경우 학습을 진행하며, --no-mf를 입력하는 경우 해당 모델의 학습을 진행하지 않습니다.(입력하지 않았을 경우에는 학습 진행을 하도록 되어 있습니다.)
- -k : Matrix Factorization 행렬의 크기를 결정하는 인자값입니다. (default = 200)
- -e 또는 --epochs : mf 모델의 학습 횟수를 결정하는 인자입니다. (default = 1)
- -b 또는 --batch_size : 학습 시 사용하는 batch_size를 결정하는 인자입니다.(default = 512)

**knn 모델 학습용 arguments**
- --knn : 최근접 이웃을 활용한 콘텐츠 기반 필터링 모델의 학습 여부를 결정하는 인자입니다. --knn을 입력하는 경우 학습을 진행하며, word2vec 모델과 cbf_data, knn모델을 models 폴더 경로에 생성합니다.(이미 존재하는 경우에는 업데이트) --no-knn을 입력하면 해당 모델의 학습을 진행하지 않습니다.(입력하지 않았을 경우에는 학습 진행을 하도록 되어 있습니다.)
- --vector_size : word2vec 학습에 생성하는 행렬 차원의 수를 결정하는 인자입니다.(default = 100)
- --pretrained : 영화 장르 임베딩을 적용할 때 사용하는 gensim의 사전학습 모델을 결정하는 인자입니다. (default = 'glove-twitter-100')

In [3]:
#CLI
#mf모델만 3 epochs로 학습하라는 명령어(knn 모델은 학습하지 않음)
#두가지 모델을 전무 학습시키고 싶다면 !python trian.py 명령어를 사용하시면 됩니다.
!python train.py --no-knn -e 3

2023-06-28 07:53:59.530928: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-28 07:53:59.574179: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-06-28 07:53:59.574713: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-06-28 07:54:00.381440: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Epoch 1/3
1251/1251 [==============================] - 25s 19ms/step - loss: 5.7587 - val_loss: 0.9398
Epoch 2/3
1251/1251 [==============================] - 23s 18ms/step - loss: 0.8581 - val_loss: 0.8353
Epoch 3/3
1251/1251 [==============================] - 25s 20ms/step - loss: 0.7570 - 

### 인기도 기반 추천 시스템 테스트
베이스라인 모델의 인기도 기반 추천은 사용자들이 가장 많이 평점을 남긴 영화 순으로 추천하도록 설계되어 있습니다.</br>
관련 코드는 models 폴더의 impersonal.py 코드에 작성되어 있습니다.

In [1]:
from models.impersonal import popular
popular(10)

[2858, 260, 1196, 1210, 480, 2028, 589, 2571, 1270, 593]

### 협업 필터링 모델 테스트
Matrix Factorization 기반 모델 코드의 경우 train.py를 통해 학습한 mf.h5 파일을 로드하여 예측을 진행합니다.

In [10]:
from models.MF import MF

mf = MF('./models/mf.h5')

In [41]:
userid = 1004
mf.predict(userid)

[527, 318, 1207, 1198, 50, 858, 1148, 260, 2324, 910]

### 콘텐츠 기반 필터링 모델 테스트
최근접 이웃 알고리즘을 활용한 콘텐츠 기반 필터링 모델의 경우 train.py를 통해 학습한 knn.joblib 파일을 로드하여 예측을 진행합니다.

In [10]:
from models.KNN import KNN

knn = KNN('models/knn.joblib')

In [11]:
USER_ID = 1
TOP_NUM=10
knn.predict(USER_ID, TOP_NUM)

array([1187, 1244, 1197,   69,  255, 1178, 1985, 1192,  667,  606])

### LightFM

#### pip install

In [6]:
!pip install -r ./requirements.txt
# !pip install -r ../requirements.txt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 537.5 kB/s eta 0:00:0000:0100:01
  Using cached category_encoders-2.6.0-py2.py3-none-any.whl (81 kB)
  Using cached certifi-2022.5.18.1-py3-none-any.whl (155 kB)
  Using cached cloudpickle-2.2.1-py3-none-any.whl (25 kB)
  Using cached comm-0.1.3-py3-none-any.whl (6.6 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 1.1 MB/s eta 0:00:0000:0100:01
  Using cached future-0.18.3.tar.gz (840 kB)
  Preparing metadata (setup.py) ... done
  Using cached hyperopt-0.2.7-py2.py3-none-any.whl (1.6 MB)
  Using cached ipykernel-6.22.0-py3-none-any.whl (149 kB)
  Using cached ipython-8.11.0-py3-none-any.whl (793 kB)
  Using cached jedi-0.18.2-py2.py3-none-any.whl (1.6 MB)
  Using cached joblib-1.2.0-py3-none-any.whl (297 kB)
  Using cached jupyter_client-8.1.0-py3-none-any.whl (102 kB)
  Using cached jupyter_core-5.3.0-py3-none-any.whl (93 kB)
  Using cached networkx-3.0-py3-none-any.whl (2.0 MB)
  Using cached packaging-23.0-py3-no

In [3]:
!pip install chardet

  Obtaining dependency information for chardet from https://files.pythonhosted.org/packages/38/6f/f5fbc992a329ee4e0f288c1fe0e2ad9485ed064cac731ed2fe47dcc38cbf/chardet-5.2.0-py3-none-any.whl.metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.4/199.4 kB 1.1 MB/s eta 0:00:00ta 0:00:01


In [12]:
!pip list | grep lightfm
!pip list | grep numpy
!pip list | grep chardet
!pip list | grep matplotlib

lightfm                       1.17
numpy                         1.24.3
chardet                       5.2.0
matplotlib                    3.7.2
matplotlib-inline             0.1.6


#### LFM test

다른 모델 모듈 호출 시 pip install 필요 현재 예측까지만 가능

In [9]:
# cmd
# !python train.py --no-knn --no-mf --no-svd --no-mlp -e 10
!python train.py --no-knn --no-mf -e 10

2023-08-24 15:26:46.068811: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/Users/leekawo/anaconda3/envs/pj2_test/lib/python3.9/site-packages/lightfm/_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn(
---LightFM Model Training...---
Epoch: 100%|████████████████████████████████████| 10/10 [00:38<00:00,  3.85s/it]
Training set AUC: 0.9545115232467651
---LightFM Model and Dataset Training Complete---


In [11]:
from models.LightFM import LightFM_Model

lightfm = LightFM_Model(model_path="./models/lightfm_model.joblib", dataset_path="./models/lightfm_dataset.joblib")

USER_ID = 1
TOP_NUM = 10
movie_lightfm_pred = lightfm.predict(USER_ID, TOP_NUM)
movie_lightfm_pred

/Users/leekawo/anaconda3/envs/pj2_test/lib/python3.9/site-packages/lightfm/_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn(


array([1959,  847,  108, 3349, 1885,  315, 1656, 1568,  770,   20])

In [10]:
# LightFM 모델 단독 예측 실행
!python models/LightFM.py -u 1 -n 10

/Users/leekawo/anaconda3/envs/pj2_test/lib/python3.9/site-packages/lightfm/_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn(
[1959  847  108 3349 1885  315 1656 1568  770   20]
